"""empty message

Revision ID: 157ddab04c80
Revises: 
Create Date: 2021-01-29 03:22:14.137332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157ddab04c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('IdOp', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('claseOp', sa.Enum('COMPRA', 'VENTA', 'NOMINA', name='claseoperacion'), nullable=True),
    sa.PrimaryKeyConstraint('IdOp')
    )
    op.create_table('clientes',
    sa.Column('CIF_cli', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CIF_cli')
    )
    op.create_table('empleados',
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('puesto', sa.String(), nullable=True),
    sa.Column('sueldo', sa.Float(), nullable=True),
    sa.Column('duracion', sa.String(), nullable=True),
    sa.Column('fechaInicio', sa.String(), nullable=True),
    sa.Column('actividad', sa.Enum('ACTIVO', 'INACTIVO', name='empleadoestados'), nullable=True),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('facturas',
    sa.Column('CIF_cli', sa.String(), nullable=True),
    sa.Column('IDlote', sa.Integer(), nullable=False),
    sa.Column('FechaVen', sa.Date(), nullable=True),
    sa.Column('ImporteVen', sa.Float(), nullable=True),
    sa.Column('IdOp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IDlote')
    )
    op.create_table('materiaprima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('caracteristicas', sa.String(), nullable=True),
    sa.Column('zonaAlmacenaje', sa.String(), nullable=True),
    sa.Column('cantidadA', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nominas',
    sa.Column('IBAN', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=True),
    sa.Column('DNI', sa.String(), nullable=False),
    sa.Column('IdOp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fecha', 'DNI')
    )
    op.create_table('proveedores',
    sa.Column('CIF_pro', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CIF_pro')
    )
    op.create_table('proyecto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('INICIAL', 'EN_PROCESO', 'EN_PAUSA', 'FINALIZADO', 'FRACASO', name='proyectoestados290121'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recibos',
    sa.Column('CIF_pro', sa.String(), nullable=True),
    sa.Column('NumeroRegistro', sa.Integer(), nullable=False),
    sa.Column('FechaCom', sa.Date(), nullable=True),
    sa.Column('ImporteCom', sa.Float(), nullable=True),
    sa.Column('IdOp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NumeroRegistro')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('fechaIni', sa.String(), nullable=True),
    sa.Column('fechaFin', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dni'], ['empleados.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercancia',
    sa.Column('numRegistro', sa.Integer(), nullable=False),
    sa.Column('idmp', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('AÑADIDO', 'RETIRADA', name='mercanciatipos'), nullable=True),
    sa.Column('idpp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['idmp'], ['materiaprima.id'], ),
    sa.PrimaryKeyConstraint('numRegistro')
    )
    op.create_table('producto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cod_distribucion', sa.String(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['origen'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idproducto', sa.String(), nullable=False),
    sa.Column('fechaProd', sa.Date(), nullable=True),
    sa.Column('fechaCad', sa.Date(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ALMACENADO', 'REPARTIDO', name='lotesestados'), nullable=True),
    sa.ForeignKeyConstraint(['idproducto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceso_productivo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('ctd_producida', sa.Float(), nullable=True),
    sa.Column('fabrica', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fabrica'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceso_productivo')
    op.drop_table('lote')
    op.drop_table('producto')
    op.drop_table('mercancia')
    op.drop_table('evaluaciones')
    op.drop_table('recibos')
    op.drop_table('proyecto')
    op.drop_table('proveedores')
    op.drop_table('nominas')
    op.drop_table('materiaprima')
    op.drop_table('facturas')
    op.drop_table('empleados')
    op.drop_table('clientes')
    op.drop_table('balances')
    # ### end Alembic commands ###
